# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180326_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('mk-mk', 'Македонски'), ('sq-sq', 'Shqip')], default='en-us', max_length=10),
        ),
    ]
