# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('mk', 'Македонски'), ('sq', 'Shqip')], default='mk', max_length=10),
        ),
    ]
