# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-04-23 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180423_1909'),
        ('home', '0004_auto_20180423_1907'),
    ]

    operations = [
    ]
