# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 12:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Невалиден телефонски број. Пример: '+38970123123'", regex='^\\+?1?\\d{9,15}$')])),
                ('manufacturer', models.CharField(blank=True, max_length=25)),
                ('model', models.CharField(blank=True, max_length=25)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
