# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20180304_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
