# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20180306_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
